# version: '3.8'
services:
  # spark-master:
  #   image: bitnami/spark:latest
  #   container_name: spark-master
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_MASTER_HOST=spark-master
  #   ports:
  #     - "6066:6066"  # Spark UI
  #     - "7077:7077"  # Spark Master Port
  #   networks:
  #     - spark-net

  # spark-worker:
  #   image: bitnami/spark:latest
  #   container_name: spark-worker
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #   depends_on:
  #     - spark-master
  #   networks:
  #     - spark-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airflow
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./DB/postgres:/var/lib/postgresql/data  # Volume for persistent data
    networks:
      - spark-net

  airflow:
    image: apache/airflow:latest
    ports:
      - "8081:8081"
    volumes:
      - ./airflow/:/opt/airflow/
    depends_on:
      - postgres
    networks:
      - spark-net
    entrypoint: bash -c "/opt/airflow/airflow_setup.sh"
    restart: always

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: airflow
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - spark-net

  # mongodb:
  #   image: mongo:6
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - spark-net

networks:
  spark-net:
    driver: bridge

