# version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app
      - ./scripts:/scripts
    ports:
      - "8080:8080"

  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    depends_on:
      - postgres
    volumes:
      - ./airflow/:/opt/airflow/
      - ./scripts:/scripts
    ports:
      - "8081:8081"
    networks:
      - shared-net
    entrypoint: bash -c "/opt/airflow/airflow_setup.sh"

  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    volumes:
      - ./airflow/:/opt/airflow/
      - ./scripts:/scripts
    networks:
      - shared-net
    command: scheduler
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: defaultDB
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./DB/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shared-net

  # spark-master:
  #   image: bitnami/spark:latest
  #   container_name: spark-master
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_MASTER_HOST=spark-master
  #   ports:
  #     - "6066:6066"  # Spark UI
  #     - "7077:7077"  # Spark Master Port
  #   networks:
  #     - spark-net

  # spark-worker:
  #   image: bitnami/spark:latest
  #   container_name: spark-worker
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #   depends_on:
  #     - spark-master
  #   networks:
  #     - spark-net
  
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: airflow
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - spark-net

  # mongodb:
  #   image: mongo:6
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - spark-net

networks:
  shared-net:
    driver: bridge
  spark-net:
    driver: bridge

